site_name: PyCafe plugin for MkDocs
site_url: https://mkdocs.py.cafe
theme:
  name: material
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: python
          class: 'highlight'
          validator: !!python/name:mkdocs_pycafe.validator
          format: !!python/object/apply:mkdocs_pycafe.formatter
            kwds:
              type: solara
              requirements: |
                altair
                anywidget
  - pymdownx.snippets:
      url_download: true
